account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, UserProfileView, ReturnLoanView, LoggingInView

app_name = 'account'
urlpatterns = [
    path('return_loan/', ReturnLoanView.as_view(), name='return_loan'),
    path('login/', LoggingInView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

borrow/urls.py
from django.urls import path

from . import views

app_name = 'borrow'  # namespace for urls
urlpatterns = [
    # product page
    path('product/<int:pk>/', views.ProductView.as_view(), name='product'),
    # the loaning view for the product
    path('product/<int:pk>/loan/', views.create_loan, name='loan'),
    # the return view for the product
    path('product/<int:pk>/return/', views.return_loan, name='return'),
    # the list view for all of the products
    path('list', views.ProductListView.as_view(), name='list'),
    # use the index page as root for the borrow application
    path('', views.IndexView.as_view(), name='index'),
]

lainakoodarit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # login, sign up and account profile urls in their own urls.py
    path('account/', include('account.urls')),
    # for browser reload to work in the "DEBUG = True" server
    path("__reload__/", include("django_browser_reload.urls")),
    # using the borrowing application as the root application
    path('', include('borrow.urls')),
]

# allow media loading in the development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

borrow/models.py
from django.db import models
import datetime
from .image_process import save_thumbnail
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional fields you'd like for the user profile

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()


class Author(models.Model):
    author_name = models.CharField(max_length=50)
    home_country = models.CharField(max_length=60, blank=True, null=True)

    class Meta:
        ordering = ["author_name"]

    def __str__(self):
        return self.author_name


class Product(models.Model):
    # NON NULLABLE values - must be filled
    name = models.CharField(max_length=50)
    genre = models.CharField(max_length=30)
    description = models.TextField(
        max_length=750, default="description not available")
    date_added = models.DateField(auto_now_add=True)
    author = models.ManyToManyField(Author)
    category = models.CharField(max_length=30)
    amount = models.SmallIntegerField(default=0)
    loaned_amount = models.SmallIntegerField(default=0, editable=False)
    # NULLABLE fields - can be left empty
    genre = models.CharField(max_length=30, blank=True, null=True)
    language = models.CharField(max_length=30, blank=True, null=True)
    # we could use a randomly chosen thumbnail for if there is no image provided
    image = models.ImageField(
        upload_to="images/", blank=True, null=True)
    thumbnail = models.CharField(
        max_length=75, blank=True, null=True, editable=False)
    # purchase_event

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Save a thumbail for the product that is smaller and faster to load"""
        super().save(*args, **kwargs)
        if self.image:
            thumb_path = save_thumbnail(self.image.path, self.image.name)
            self.thumbnail = thumb_path
            super().save(*args, **kwargs)


class Event(models.Model):
    # TODO: the same system as in
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, default=None)
    product = models.ForeignKey(
        to=Product, on_delete=models.CASCADE, default=None)
    loaned_date = models.DateField(auto_now_add=True)
    return_date = models.DateTimeField(blank=True, null=True, editable=False)
    actual_return_date = models.DateTimeField(
        blank=True, null=True, editable=False)
    # updates the value when model is saved
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['actual_return_date', '-last_update']

    def __str__(self):
        return f'event: user_id: {self.user}, last update: {self.last_update}'

borrow/views.py
# Create your views here.
from django.db.models import F, ObjectDoesNotExist
from django.views import generic
from .models import Product, Event, Author
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import datetime, timedelta


class IndexView(generic.ListView):
    template_name = 'borrow/index.html'
    # what name to use in the template for the data returned in get_queryset
    context_object_name = 'listings'

    def get_queryset(self):
        """ Return the five most recent objects in the product category """
        return Product.objects.order_by('-date_added')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        authors = Author.objects.all()
        context['authors'] = authors
        return context


class ProductView(generic.DetailView):
    # TODO: change this to a database object when database is ready
    model = Product
    context_object_name = 'product'
    template_name = 'borrow/product_page.html'

    def get_context_data(self, **kwargs):
        """Calculate the amount of copies available and add to the view context"""
        context = super().get_context_data(**kwargs)
        # get a default image for product, if image does not exist
        product = self.get_object()
        # calculate the amount of available copies
        available = product.amount - product.loaned_amount
        # add the value to be available in the context
        # use {{ available }} to use it
        context['available'] = available
        # also add a list of 5 most recent products of the same category
        current_category = context['object'].category
        context['recent_additions'] = Product.objects.filter(
            category=current_category)[:5]

        user = self.request.user
        if not user:
            return context
        user_loan = Event.objects.filter(
            user=user.id, product=product.id, actual_return_date__isnull=True)
        context['user_loaned'] = user_loan.exists()
        return context


class ProductListView(generic.ListView):
    """View for the product list page."""
    template_name = 'borrow/product_list.html'
    context_object_name = 'listings'
    ordering = '-date_added'
    model = Product

    def get_queryset(self):
        """Check if the template passed a GET query.
        If so, use the keyword variable's value to filter the database query.

        - this is created in a way that you don't have to manually type every
        case for a filter. This function loops through all Product fields and
        checks for filters programatically
        """
        queryset = super().get_queryset()
        # filter the query's author by name if one is provided
        author_name_query = self.request.GET.get('author')
        if author_name_query:
            queryset = queryset.filter(author__author_name=author_name_query)
        available_query = self.request.GET.get('available')
        if available_query:
            queryset = queryset.filter(loaned_amount__lt=F('amount'))
        # loops through the GET requests
        for key, values in self.request.GET.lists():
            # if get query keyword is author, change it to correct attribute name
            key = 'author__author_name' if key == 'author' else key
            # check if the key agument of a request is a Product attribute
            # and that the kwarg is not empty
            if not hasattr(Product, key) or not values[0]:
                # if either of these doesn't pass, continue iterating
                continue

            # if prior checks have passed, loop through the values
            # and use them as filters for the database query
            # check that the given GET values for a category are singular
            if len(values) == 1:
                filter = f'{key}__icontains'
            # if there are multiple GET values for a singular keyword
            else:
                filter = f'{key}__in'
            if len(values) == 1:
                queryset = queryset.filter(**{filter: values[0]})
            else:
                print("value is not 1")
                queryset = queryset.filter(**{filter: values})
        # return the queryset and order by the given ordering
        return queryset.order_by(self.ordering)


@login_required
def create_loan(request, pk):

    loan_times = {
        "music": datetime.today() + timedelta(days=7),
        "book": datetime.today() + timedelta(days=30),
        "movie": datetime.today() + timedelta(days=3)
    }

    # first get the product
    product = get_object_or_404(Product, pk=pk)
    redirect_url = reverse_lazy('borrow:product', kwargs={'pk': product.pk})
    try:
        # then create a loan event
        loan_time = loan_times[product.category]
        loan = Event.objects.create(
            user=request.user, product=product, return_date=loan_time)
        loan.save()
    except ObjectDoesNotExist:
        return redirect(redirect_url + '?success=false&event=loan')
    # when everything is done successfully, add the loan to the loaned amount
    product.loaned_amount += 1
    product.save()
    # redirect the user back to the product page afterwards
    return redirect(redirect_url + '?success=true&event=loan')


@login_required
def return_loan(request, pk):
    # first get the product
    product = get_object_or_404(Product, pk=pk)
    redirect_url = reverse_lazy('borrow:product', kwargs={'pk': product.pk})
    try:
        # then update the loaned event to have a return date
        loan = Event.objects.get(
            user=request.user, product=product, actual_return_date__isnull=True)
        loan.actual_return_date = timezone.now()
        loan.save()
    except ObjectDoesNotExist:
        return redirect(redirect_url + '?success=false&event=return')
    # when everything is done successfully, remove the loan from the loaned_amount
    product.loaned_amount -= 1
    product.save()
    # redirect the user back to the product page afterwards
    return redirect(redirect_url + '?success=true&event=return')

borrow/templates/borrow/index.html
{% extends "base.html" %}
{% block title %}Borrow System{% endblock %}
{% block scripts %}
  {% load static %}
  <script src="{% static 'js/carousel.js' %}" defer></script>
{% endblock %}
{% block content %}
<main class="grid md:grid-flow-col grid-cols-5 gap-x-5 gap-y-5 px-5 max-w-[1200px] mx-auto">
  <!-- search form -->
  <form action="{% url 'borrow:list' %}" method="get" class="col-span-6 grid grid-flow-row gap-y-2 shadow-lg 
    rounded-lg p-5 md:col-span-3 lg:col-span-2">
    <!-- Name -->
    <div class="flex flex-col">
      <label for="name">Search name</label>
      <input type="text" name="name" id="name" autofocus
      class="px-2 py-1 outline outline-1 outline-red-400 rounded hover:outline-2 focus:outline-2"/>
    </div>
    <!-- Author-->
    <div class="flex flex-col">
      <label for="author_name">Author</label>
      <select data-te-select-init class="bg-transparent px-2 py-1 outline outline-1 outline-red-400 rounded 
        hover:outline-2 focus:outline-2" id="author" name="author">
        <option value="" class="italic">--Select All--</option>
        {% for listing in authors|dictsort:"author_name" %}
        <!-- make sure that there cannot be multiple listings of the same genre -->
        {% ifchanged listing.author_name %}
          <option value="{{ listing.author_name }}">{{ listing.author_name|title }}</option>
        {% endifchanged %}
        {% endfor %}
      </select>
    </div>
    <!-- Genre-->
    <div class="flex flex-col">
      <label for="genre">Genre</label>
      <select data-te-select-init class="bg-transparent px-2 py-1 outline outline-1 outline-red-400 rounded 
        hover:outline-2 focus:outline-2" id="genre" name="genre">
        <option value="" class="italic">--Select All--</option>
        {% for listing in listings|dictsort:"genre" %}
        <!-- make sure that there cannot be multiple listings of the same genre -->
        {% ifchanged listing.genre %}
          <option value="{{ listing.genre }}">{{ listing.genre|title }}</option>
        {% endifchanged %}
        {% endfor %}
      </select>
    </div>
    <!-- Language-->
    <div class="flex flex-col">
      <label for="language">Language</label>
      <select data-te-select-init class="bg-transparent px-2 py-1 outline outline-1 outline-red-400 rounded 
        hover:outline-2 focus:outline-2" id="language" name="language">
        <option value="" class="italic">--Select All--</option>
        {% for listing in listings|dictsort:"language" %}
        <!-- make sure that there cannot be multiple listings of the same genre -->
        {% ifchanged listing.language %}
          <option value="{{ listing.language }}">{{ listing.language|title }}</option>
        {% endifchanged %}
        {% endfor %}
      </select>
    </div>
    <!-- Category -->
    <div class="flex gap-x-2 [&>input]:accent-red-200 mx-auto">
      <label for="category_books" class="transition-all hover:text-red-700">Books</label>
      <input type="checkbox" name="category" id="category_books" value="book"/>
      <label for="category_music" class="transition-all hover:text-red-700">Music</label>
      <input type="checkbox" name="category" id="category_music" value="music"/>
      <label for="category_movies" class="transition-all hover:text-red-700">Movies</label>
      <input type="checkbox" name="category" id="category_movies" value="movie" 
        class="transition-all hover:text-red-700"/>
    </div>
    <!-- Available -->
    <div class="flex gap-x-2 [&>input]:accent-red-200 mx-auto">
      <label for="available" class="transition-all hover:text-red-700">Only list available products</label>
      <input type="checkbox" name="available" id="available" value="available"
      class="transition-all hover:font-semibold"/>
    </div>
    
    <button type="submit" class="bg-red-400 text-neutral-100 font-semibold w-full px-4 py-2 rounded
    transition-all hover:shadow-lg hover:text-neutral-900 active:brightness-75">Search</button>
  </form>
  <!-- user guide -->
  <div class="col-span-5 flex flex-col gap-y-2 justify-center order-first mt-10 text-center md:order-last lg:col-span-3">
    <div>
      <h2 class="text-lg text-center font-semibold">Guide</h2>
      <p>
        This is a simple borrowing system. Here you can search for names of books, music and movies. 
        You can also filter by author, genre, language and category. 
        It is also possible to filter results to only show available products.
        Use these filters to search and find a product that fits your needs and interests!
      </p>
    </div>
    <p>Don't have an account? 
      <a href="{% url 'account:signup' %}" class="text-red-500 transition-all hover:brightness-75 hover:underline">Create one here</a>
    </p>
  </div>
</main>

<!-- most recent additions -->
<section class="max-w-[1200px] mx-auto mt-10 px-5">
  <h3 class="font-semibold mb-2">Recent additions</h3>
  <div class="carousel grid grid-flow-col text-center pb-6 overflow-auto gap-x-4">
    {% for listing in listings|slice:":5" %}
    <a href="{% url 'borrow:product' listing.id %}" draggable="false"
      class="select-none shadow-md w-[200px] aspect-square group hover:shadow-lg">
      <div class="overflow-hidden aspect-square relative group">
        {% if listing.thumbnail %}
        <!-- if listing has a thumbnail -->
        <img src="{{ listing.thumbnail }}" alt="{{ listing.title }} -thumbnail" 
          width="300" height="300" draggable="false"
          class="object-cover w-full h-full transition-all group-hover:scale-110">
        {% else %}
        <!-- if listing doesn't have a thumbnail -->
        {% load static %}
        <div class="object-cover w-full h-full flex flex-col justify-center bg-neutral-200
          opacity-50 transition-all hover:scale-110">
          <img src="{% static 'icons/default-' %}{{ listing.category }}.svg" alt="{{ listing.title }} -thumbnail" 
            width="300" height="300" draggable="false"
            class="w-full h-1/4"/>
          <p class="font-semibold">Image not provided</p>
        </div>
        {% endif %}
        <!-- listing genre -->
        <p class="absolute bottom-0 right-1/2 translate-x-1/2 py-2 bg-[#40404055] w-full text-neutral-100 truncate
          opacity-0 transition-all group-hover:opacity-100">{{ listing.genre|title }}</p>
      </div>
      <!-- listing title -->
      <p class="text-sm line-clamp-2 py-2 px-3 text-start h-2/6 flex items-center
        transition-all group-hover:underline">{{ listing.name }}</p>
    </a>
    {% endfor %}
  </div>
</section>
{% endblock %}

borrow/templates/borrow/product_list.html
{% extends 'base.html' %}
{% block title %}
  Products
{% endblock %}
{% block content %}
  <header class="max-w-[1200px] mx-auto px-5 my-5">
    <div class="flex items-end gap-x-2 text-lg font-semibold">
      <h1 class="text-2xl font-bold">Listings:</h1>
      <p>{{ listings.count }}</p>
      <!-- if a non empty get request is passed, give option to remove all get requests -->
      {% if request.GET %}
        <a href="{% url 'borrow:list' %}" class="text-sm ml-2 pb-1 hover:underline">Remove all filter(s) x</a>
      {% endif %}
    </div>
    <!-- show user the filters used, allow them to click it and remove the clicked on filter -->
    <!-- I admit, it is not pretty and I am not proud of it, but it works -->
    <div class="flex gap-x-3 my-2">
      {% for filter, values in request.GET.lists %}
      {% for value in values %}
      {% if value  %}
      <!-- magic happens here, do not touch, just an extremely nice and easy to read url -->
      <a href="{% url 'borrow:list' %}?{% for key, val in request.GET.lists %}{% for val2 in val %}{% if val2 != value %}{{ key }}={{ val2 }}&{% endif %}{% endfor %}{% endfor %}">
        <div class="py-2 px-4 bg-red-100 rounded-md text-sm flex gap-x-3 shadow-sm transition-all hover:bg-red-200">
          <p>{{ filter|title }}: <span class="font-semibold">{{ value|title }}</span>
          </p>
          <p>x</p>
        </div>
      </a>
      {% endif %}
      {% endfor %}
      {% endfor %}
    </div>
  </header>
  <section class="max-w-[1200px] mx-auto px-5 mb-20">
    <div class="grid gap-5 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    {% for listing in listings %}
      <a href="{% url 'borrow:product' listing.id %}" draggable="false"
        class="product-card shadow-md flex flex-col select-none group">
        <!-- product image -->
        <div class="product-img overflow-hidden aspect-[4/3] sm:aspect-square group relative
          {% if listing.loaned_amount == listing.amount %} opacity-50 {% endif %}">
          {% if listing.image %}
            <img src="{{ listing.image.url }}" alt="{{ listing.name}} -thumbnail" width="200" height="200" draggable="false"
              class="object-cover w-full h-full transition-all group-hover:scale-110"/>
          {% else %}
          {% load static %}
          <div class="object-cover w-full h-full flex flex-col justify-center bg-neutral-200
            opacity-50 transition-all group-hover:scale-110">
            <img src="{% static 'icons/default-' %}{{ listing.category }}.svg" alt="{{ listing.name}} -thumbnail" width="200" height="200" draggable="false"
              class="w-full h-1/4"/>
            <p class="text-center font-semibold">No image provided</p>
          </div>
          {% endif %}
          <!-- product genre -->
          <p class="absolute bottom-0 right-1/2 translate-x-1/2 py-2 bg-[#40404055] text-white w-full
            font-semibold text-center opacity-0 transition-all group-hover:opacity-100">{{ listing.genre|title }}</p>
        </div>
        <!-- product title -->
        <div class="product-title px-4 py-2 flex items-center h-16 sm:h-20">
          <h3 class="line-clamp-1 group-hover:underline sm:line-clamp-2">{{ listing.name }}</h3>
        </div>
      </a>
    {% endfor %}
    </div>
  </section>
{% endblock %}

borrow/templates/borrow/product_page.html
{% extends "base.html" %}
{% block title %}{{ product.name }} - {{ product.category }}{% endblock %}
{% block scripts %}
  {% load static %}
  <script src="{% static 'js/products.js' %}" defer></script>
  <script src="{% static 'js/carousel.js' %}" defer></script>
  <script src="{% static 'js/alert.js' %}" defer></script>
{% endblock %}

{% block content %}
<!-- if page is reloaded after a successfull loan action -->
{% if request.GET.success %}
<section class="alert fixed top-8 right-1/2 translate-x-1/2 bg-white shadow-lg z-10 
  py-5 pl-10 pr-8 font-semibold rounded-lg transition-all duration-500 opacity-0 -translate-y-6">
    <div class="flex w-full gap-x-2">
    {% if request.GET.success == 'true' %}
      {{ request.GET.event|title }} successful! &#9989;
    {% else %}
      Error occurred while {{ request.GET.event }}! &#10060;
    {% endif %}
    <button type="button" class="px-2 opacity-75">x</button>
    </div>
  </section>
{% endif %}

<article class="max-w-[1200px] mx-auto">
  <!-- product category in the database -->
  <p class="my-2 mx-5 xl:mx-0">
    <a href="{% url 'borrow:list' %}?category={{ product.category }}">
      {{ product.category|title }}</a> &gt; <a href="{% url 'borrow:list' %}?genre={{ product.genre }}">{{ product.genre|title }}
    </a>
  </p>
  <div class="grid md:grid-cols-4 gap-y-8">
    <div class="md:col-span-2">
      {% load static %}

      <!-- Product image -->
      <div class="img-container w-full aspect-[4/3] overflow-hidden relative group">
        {% if product.image %}
        <!-- if image is found, show 'image not provided image' -->
        <a href="{{ product.image.url }}">
          <img src="{{ product.image.url }}" alt="product image for {{ product.name }}" width="300" height="200"
            class="object-cover h-full w-full transition-all hover:scale-110"/>
        </a>
        <p class="absolute bottom-0 right-1/2 translate-x-1/2 
          py-3 px-4 w-full text-white text-center bg-[#40404055] transition-all opacity-0
          group-hover:underline group-hover:opacity-100">
          View full image
        </p>
        {% else %}
        <!-- if no image is found -->
        <div class="object-cover h-full w-full flex flex-col justify-center bg-neutral-200
          opacity-50 transition-all hover:scale-110">
          <img src="{% static 'icons/default-' %}{{ product.category }}.svg" alt="default product image for a {{ product.category }}" width="200" height="200"
            class="w-full h-1/4 motion-safe:animate-bounce"/>
          <p class="w-full text-center font-semibold select-none">No image provided</p>
        </div>
        {% endif %}
      </div>
    </div>

    <!-- product info -->
    <div class="px-10 flex items-center md:col-span-2">
      <div class="product-card shadow-lg w-full rounded-lg p-4
        flex flex-col gap-y-5">
        <div class="prouct-header">
          <h1 class="text-2xl font-bold">{{ product.name }}</h1>
          <p class="opacity-50 font-semibold">{{ product.category|title }} | {{ product.genre|title }}</p>
        </div>
        <!-- <hr class="my-5 border-neutral-300"/> -->
        <!-- creator info -->
        <div class="product-creator flex items-center gap-x-5">
          <h2 class="font-semibold">Author:</h2>
          <p>
            {% for author in product.author.all %}
            {{ author.author_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </p>
        </div>
        {% if available and request.user.is_authenticated and not user_loaned %}
          <form method="post" action="{% url 'borrow:loan' pk=product.pk %}">
            {% csrf_token %}
            <button type="submit" class="bg-red-400 py-2 px-4 w-full rounded text-white font-semibold 
              shadow-md transition-all hover:text-neutral-900 active:scale-90">Loan this</button>
          </form>
        {% elif user_loaned %}
        <form method="post" action="{% url 'borrow:return' pk=product.pk %}">
          {% csrf_token %}
          <button type="submit" class="outline outline-1 outline-red-400 py-2 px-4 w-full rounded text-red-400 font-semibold 
            shadow-md transition-all hover:outline-0 hover:bg-red-400 hover:text-white active:scale-90">Return loan</button>
        </form>
        {% elif not request.user.is_authenticated %}
          <button class="bg-black py-2 px-4 rounded text-neutral-100 font-semibold opacity-50
            transition-all">Unavailable</button>
          <p class="text-center -translate-y-5">* Not logged in, loaning unavailable</p>
        {% else %}
          <button class="bg-black py-2 px-4 rounded text-neutral-100 font-semibold opacity-50
            transition-all">Unavailable</button>
          <p class="text-center -translate-y-5">* No copies available currently</p>
        {% endif %}
        <p class="text-red-500">{{ loaned_amount }}</p>
      </div>
    </div>
  </div>
</article>

<!-- description -->
<article class="max-w-[1000px] mx-auto my-10 px-5 sm:px-10">
  <h3 class="font-semibold text-center">Description</h3>
  <div class="my-2 space-y-4" id="description">
    {{ product.description|linebreaks }}
  </div>
  <hr id="description_line" class="my-5 border-neutral-300"/>
  <button id="readmore" class="underline block mx-auto">Read more</button>
</article>

<!-- additional information -->
<section class="max-w-[700px] mx-auto my-8 px-5">
  <h3 class="font-semibold text-center mb-5">Additional information</h3>
  <div class="grid grid-cols-2 mx-auto gap-y-6 gap-x-5 sm:grid-cols-4">
    {% if product.date_added %}
    <div class="flex flex-col gap-x-2 items-center">
      <!-- icon -->
      <div class="text-center">
        <h4 class="mb-2 font-semibold">Date added</h4>
        <img src="{% static 'icons/date_added.svg' %}" alt="tags -icon" width="30" height="30"
        class="mx-auto"/>
        <!-- <i class="bi bi-calendar-plus-fill text-xl"></i> -->
      </div>
      <!-- content -->
      <div class="flex gap-x-5">
        <p class="justify-center">
          {{ product.date_added }}
        </p>
      </div>
    </div>
    {% endif %}
    {% if product.category %}
    <div class="flex flex-col gap-x-2 justify-evenly items-center">
      <!-- icon -->
      <div class="text-center">
        <h4 class="mb-2 font-semibold">Category</h4>
        <img src="{% static 'icons/tag.svg' %}" alt="category -icon" width="30" height="30"
        class="mx-auto"/>
      </div>
      <!-- content -->
      <div class="flex gap-x-5">
        <p class="justify-center">
          {{ product.category|title }}
        </p>
      </div>
    </div>
    {% endif %}
    {% if product.language %}
    <div class="flex flex-col gap-x-2 justify-evenly items-center">
      <!-- icon -->
      <div class="text-center">
        <h4 class="mb-2 font-semibold">Language</h4>
        <img src="{% static 'icons/language.svg' %}" alt="tags -icon" width="30" height="30"
        class="mx-auto"/>
      </div>
      <!-- content -->
      <div class="flex gap-x-5">
        <p class="justify-center">
          {{ product.language|title }}
        </p>
      </div>
    </div>
    {% endif %}
    {% if product %}
    <div class="flex flex-col gap-x-2 justify-evenly items-center">
      <!-- icon -->
      <div class="text-center">
        <h4 class="mb-2 font-semibold">Availability</h4>
        {% if available %}
        <img src="{% static 'icons/storage.svg' %}" alt="tags -icon" width="30" height="30"
          class="mx-auto"/>
        {% else %}
        <img src="{% static 'icons/storage.svg' %}" alt="tags -icon" width="30" height="30"
          class="mx-auto opacity-50"/>
        {% endif %}
      </div>
      <!-- content -->
      <div class="flex gap-x-5 mx-auto">
        <p class="justify-center">
          {{ available }} / {{ product.amount }}
        </p>
      </div>
    </div>
    {% endif %}
  </div>
</section>

<!-- most recent additions -->
<section class="max-w-[1200px] mx-auto my-10 px-5">
  <h3 class="font-semibold mb-2">Recent additions</h3>
  <div class="carousel grid grid-flow-col text-center pb-6 overflow-auto gap-x-4">
    {% for listing in recent_additions %}
    <a href="{% url 'borrow:product' listing.id %}" draggable="false"
      class="select-none shadow-md w-[200px] aspect-square group hover:shadow-lg">
      <div class="overflow-hidden aspect-[4/3] relative group">
        {% if listing.thumbnail %}
        <!-- if listing has a thumbnail -->
        <img src="{{ listing.thumbnail }}" alt="{{ listing.title }} -thumbnail" 
          width="300" height="300" draggable="false"
          class="object-cover w-full h-full transition-all group-hover:scale-110">
        {% else %}
        <!-- if listing doesn't have a thumbnail -->
        {% load static %}
        <div class="object-cover w-full h-full flex flex-col justify-center bg-neutral-200
          opacity-50 transition-all hover:scale-110">
          <img src="{% static 'icons/default-' %}{{ listing.category }}.svg" alt="{{ listing.title }} -thumbnail" 
            width="300" height="300" draggable="false"
            class="w-full h-1/4"/>
          <p class="font-semibold">Image not provided</p>
        </div>
        {% endif %}
        <!-- listing genre -->
        <p class="absolute bottom-0 right-1/2 translate-x-1/2 py-2 bg-[#40404055] w-full text-neutral-100 truncate
          opacity-0 transition-all group-hover:opacity-100">{{ listing.genre|title }}</p>
      </div>
      <!-- listing title -->
      <p class="text-sm line-clamp-2 py-2 px-3 text-start h-2/6 flex items-center
        transition-all group-hover:underline">{{ listing.name }}</p>
    </a>
    {% endfor %}
  </div>
</section>
{% endblock %}