account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, UserProfileView, ReturnLoanView, LoggingInView

app_name = 'account'
urlpatterns = [
    path('return_loan/', ReturnLoanView.as_view(), name='return_loan'),
    path('login/', LoggingInView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

borrow/urls.py
from django.urls import path

from . import views

app_name = 'borrow'  # namespace for urls
urlpatterns = [
    # product page
    path('product/<int:pk>/', views.ProductView.as_view(), name='product'),
    # the loaning view for the product
    path('product/<int:pk>/loan/', views.create_loan, name='loan'),
    # the return view for the product
    path('product/<int:pk>/return/', views.return_loan, name='return'),
    # the list view for all of the products
    path('list', views.ProductListView.as_view(), name='list'),
    # use the index page as root for the borrow application
    path('', views.IndexView.as_view(), name='index'),
]

lainakoodarit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # login, sign up and account profile urls in their own urls.py
    path('account/', include('account.urls')),
    # for browser reload to work in the "DEBUG = True" server
    path("__reload__/", include("django_browser_reload.urls")),
    # using the borrowing application as the root application
    path('', include('borrow.urls')),
]

# allow media loading in the development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- favicon -->
    {% load static %}
    <link rel="icon" type="image/svg" href="{% static 'icons/django-logo.svg' %}">
    <!-- tailwind -->
    <script src="https://cdn.tailwindcss.com"></script>
    <!-- bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css"/>
    <!-- load page specific scripts -->
    {% block scripts %}
    {% endblock %}
    <!-- navigation bar functionality script -->
    <script src="{% static 'js/navbar.js' %}" defer></script>
  </head>
  <body class="min-h-screen min-h-[100svh] flex flex-col justify-between">
    <nav class="w-full max-w-[1000px] mx-auto flex flex-col justify-between p-5 gap-y-3 relative sm:flex-row">
      <!-- navigation toggle button for smaller screens -->
      <button class="absolute top-3 right-7 sm:hidden">
        <img src="{% static 'icons/navbutton-open.svg' %}" alt="navigation toggle button" width="40" height="40">
      </button>
      <div class="flex gap-x-2 justify-center items-center">
        <a href="{% url 'borrow:index' %}" class="text-center text-xl font-bold w-1/2 sm:w-full">Borrow System</a>
        <p class="text-center opacity-75 hidden self-center pt-1 md:block">Lainakoodarit</p>
      </div>
      <!-- navigation links to different pages -->
      <ul class="mx-auto text-center w-full opacity-0 hidden transition-all sm:opacity-100 sm:flex sm:gap-x-4
        [&>li>a]:py-2 [&>li>a]:block [&>li>a]:w-full [&>li]:rounded-md [&>li:nth-child(even)]:bg-red-50 
        sm:w-auto sm:mx-0 sm:flex-row sm:[&>li:nth-child(even)]:bg-transparent">
        <li class="hover:underline">
          <a href="{% url 'borrow:list' %}?category=book">Books</a>
        </li>
        <li class="hover:underline">
          <a href="{% url 'borrow:list' %}?category=music">Music</a>
        </li>
        <li class="hover:underline">
          <a href="{% url 'borrow:list' %}?category=movie">Movies</a>
        </li>
        {% if user.is_authenticated %}
        <li class="text-red-600 hover:underline">
          <a href="{% url 'account:profile' %}">{{user|title}} Profile</a>
        </li>
        <li class="hover:underline">
          <a href="{% url 'account:logout' %}">Logout</a>
        </li>
        {% else%}
        <li class="hover:underline">
          <a href="{% url 'account:login' %}">Login</a>
        </li>
        {% endif%}
      </ul>
    </nav>

    <div>
      {% block content %}
      {% endblock %}
    </div>

    <footer class="bg-red-400 p-5">
      <div class="mx-auto max-w-3xl flex gap-x-10 sm:justify-between flex-col gap-y-2 
        text-center sm:text-start sm:flex-row">
        <p class="font-semibold">&copy; Team Lainakoodarit</p>
        <div class="flex flex-wrap gap-y-1 gap-x-5 justify-center">
          <a href="https://github.com/AleksiHel" target="_blank" 
            class="transition-all hover:opacity-50 hover:underline">
            Aleksi Hellgren<i class="bi bi-box-arrow-up-right text-xs pl-1"></i>
          </a>
          <a href="https://github.com/sakuexe" target="_blank" 
            class="transition-all hover:opacity-50 hover:underline">
            Saku Karttunen<i class="bi bi-box-arrow-up-right text-xs pl-1"></i>
          </a>
          <a href="https://github.com/Waisatifi" target="_blank" 
            class="transition-all hover:opacity-50 hover:underline">
            Wais Atifi<i class="bi bi-box-arrow-up-right text-xs pl-1"></i>
          </a>
        </div>
      </div>
    </footer>
  </body>
</html>