account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignUpView, UserProfileView, ReturnLoanView, LoggingInView

app_name = 'account'
urlpatterns = [
    path('return_loan/', ReturnLoanView.as_view(), name='return_loan'),
    path('login/', LoggingInView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

borrow/urls.py
from django.urls import path

from . import views

app_name = 'borrow'  # namespace for urls
urlpatterns = [
    # product page
    path('product/<int:pk>/', views.ProductView.as_view(), name='product'),
    # the loaning view for the product
    path('product/<int:pk>/loan/', views.create_loan, name='loan'),
    # the return view for the product
    path('product/<int:pk>/return/', views.return_loan, name='return'),
    # the list view for all of the products
    path('list', views.ProductListView.as_view(), name='list'),
    # use the index page as root for the borrow application
    path('', views.IndexView.as_view(), name='index'),
]

lainakoodarit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # login, sign up and account profile urls in their own urls.py
    path('account/', include('account.urls')),
    # for browser reload to work in the "DEBUG = True" server
    path("__reload__/", include("django_browser_reload.urls")),
    # using the borrowing application as the root application
    path('', include('borrow.urls')),
]

# allow media loading in the development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

borrow/models.py
from django.db import models
import datetime
from .image_process import save_thumbnail
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional fields you'd like for the user profile

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.userprofile.save()


class Author(models.Model):
    author_name = models.CharField(max_length=50)
    home_country = models.CharField(max_length=60, blank=True, null=True)

    class Meta:
        ordering = ["author_name"]

    def __str__(self):
        return self.author_name


class Product(models.Model):
    # NON NULLABLE values - must be filled
    name = models.CharField(max_length=50)
    genre = models.CharField(max_length=30)
    description = models.TextField(
        max_length=750, default="description not available")
    date_added = models.DateField(auto_now_add=True)
    author = models.ManyToManyField(Author)
    category = models.CharField(max_length=30)
    amount = models.SmallIntegerField(default=0)
    loaned_amount = models.SmallIntegerField(default=0, editable=False)
    # NULLABLE fields - can be left empty
    genre = models.CharField(max_length=30, blank=True, null=True)
    language = models.CharField(max_length=30, blank=True, null=True)
    # we could use a randomly chosen thumbnail for if there is no image provided
    image = models.ImageField(
        upload_to="images/", blank=True, null=True)
    thumbnail = models.CharField(
        max_length=75, blank=True, null=True, editable=False)
    # purchase_event

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        """Save a thumbail for the product that is smaller and faster to load"""
        super().save(*args, **kwargs)
        if self.image:
            thumb_path = save_thumbnail(self.image.path, self.image.name)
            self.thumbnail = thumb_path
            super().save(*args, **kwargs)


class Event(models.Model):
    # TODO: the same system as in
    user = models.ForeignKey(
        to=User, on_delete=models.CASCADE, default=None)
    product = models.ForeignKey(
        to=Product, on_delete=models.CASCADE, default=None)
    loaned_date = models.DateField(auto_now_add=True)
    return_date = models.DateTimeField(blank=True, null=True, editable=False)
    actual_return_date = models.DateTimeField(
        blank=True, null=True, editable=False)
    # updates the value when model is saved
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['actual_return_date', '-last_update']

    def __str__(self):
        return f'event: user_id: {self.user}, last update: {self.last_update}'

borrow/views.py
# Create your views here.
from django.db.models import F, ObjectDoesNotExist
from django.views import generic
from .models import Product, Event, Author
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import datetime, timedelta


class IndexView(generic.ListView):
    template_name = 'borrow/index.html'
    # what name to use in the template for the data returned in get_queryset
    context_object_name = 'listings'

    def get_queryset(self):
        """ Return the five most recent objects in the product category """
        return Product.objects.order_by('-date_added')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        authors = Author.objects.all()
        context['authors'] = authors
        return context


class ProductView(generic.DetailView):
    # TODO: change this to a database object when database is ready
    model = Product
    context_object_name = 'product'
    template_name = 'borrow/product_page.html'

    def get_context_data(self, **kwargs):
        """Calculate the amount of copies available and add to the view context"""
        context = super().get_context_data(**kwargs)
        # get a default image for product, if image does not exist
        product = self.get_object()
        # calculate the amount of available copies
        available = product.amount - product.loaned_amount
        # add the value to be available in the context
        # use {{ available }} to use it
        context['available'] = available
        # also add a list of 5 most recent products of the same category
        current_category = context['object'].category
        context['recent_additions'] = Product.objects.filter(
            category=current_category)[:5]

        user = self.request.user
        if not user:
            return context
        user_loan = Event.objects.filter(
            user=user.id, product=product.id, actual_return_date__isnull=True)
        context['user_loaned'] = user_loan.exists()
        return context


class ProductListView(generic.ListView):
    """View for the product list page."""
    template_name = 'borrow/product_list.html'
    context_object_name = 'listings'
    ordering = '-date_added'
    model = Product

    def get_queryset(self):
        """Check if the template passed a GET query.
        If so, use the keyword variable's value to filter the database query.

        - this is created in a way that you don't have to manually type every
        case for a filter. This function loops through all Product fields and
        checks for filters programatically
        """
        queryset = super().get_queryset()
        # filter the query's author by name if one is provided
        author_name_query = self.request.GET.get('author')
        if author_name_query:
            queryset = queryset.filter(author__author_name=author_name_query)
        available_query = self.request.GET.get('available')
        if available_query:
            queryset = queryset.filter(loaned_amount__lt=F('amount'))
        # loops through the GET requests
        for key, values in self.request.GET.lists():
            # if get query keyword is author, change it to correct attribute name
            key = 'author__author_name' if key == 'author' else key
            # check if the key agument of a request is a Product attribute
            # and that the kwarg is not empty
            if not hasattr(Product, key) or not values[0]:
                # if either of these doesn't pass, continue iterating
                continue

            # if prior checks have passed, loop through the values
            # and use them as filters for the database query
            # check that the given GET values for a category are singular
            if len(values) == 1:
                filter = f'{key}__icontains'
            # if there are multiple GET values for a singular keyword
            else:
                filter = f'{key}__in'
            if len(values) == 1:
                queryset = queryset.filter(**{filter: values[0]})
            else:
                print("value is not 1")
                queryset = queryset.filter(**{filter: values})
        # return the queryset and order by the given ordering
        return queryset.order_by(self.ordering)


@login_required
def create_loan(request, pk):

    loan_times = {
        "music": datetime.today() + timedelta(days=7),
        "book": datetime.today() + timedelta(days=30),
        "movie": datetime.today() + timedelta(days=3)
    }

    # first get the product
    product = get_object_or_404(Product, pk=pk)
    redirect_url = reverse_lazy('borrow:product', kwargs={'pk': product.pk})
    try:
        # then create a loan event
        loan_time = loan_times[product.category]
        loan = Event.objects.create(
            user=request.user, product=product, return_date=loan_time)
        loan.save()
    except ObjectDoesNotExist:
        return redirect(redirect_url + '?success=false&event=loan')
    # when everything is done successfully, add the loan to the loaned amount
    product.loaned_amount += 1
    product.save()
    # redirect the user back to the product page afterwards
    return redirect(redirect_url + '?success=true&event=loan')


@login_required
def return_loan(request, pk):
    # first get the product
    product = get_object_or_404(Product, pk=pk)
    redirect_url = reverse_lazy('borrow:product', kwargs={'pk': product.pk})
    try:
        # then update the loaned event to have a return date
        loan = Event.objects.get(
            user=request.user, product=product, actual_return_date__isnull=True)
        loan.actual_return_date = timezone.now()
        loan.save()
    except ObjectDoesNotExist:
        return redirect(redirect_url + '?success=false&event=return')
    # when everything is done successfully, remove the loan from the loaned_amount
    product.loaned_amount -= 1
    product.save()
    # redirect the user back to the product page afterwards
    return redirect(redirect_url + '?success=true&event=return')

borrow/templates/profile/user_profile.html
{% extends "base.html" %}
{% block title %}My profile{% endblock %}
{% block scripts %}
{% load static %}
<script src="{% static 'js/profile-tabs.js' %}" defer></script>
{% endblock %}
{% block content %}

{% if request.GET.success %}
<section class="absolute top-12 right-1/2 translate-x-1/2 bg-white shadow-lg z-10 
  py-5 px-10 font-semibold rounded-lg">
    <div class="alert">
        {% if request.GET.success == 'true' %}
        {{ request.GET.event|title }} successful! &#9989;
        {% else %}
        Error occurred while {{ request.GET.event }}! &#10060;
        {% endif %}
    </div>
</section>
{% endif %}


<section class="relative bg-white p-2 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-md sm:rounded-lg mb-10">



    <div class="text-center font-bold mb-5 ">
        <div class="mt-3">
            <h1>{{ user.username }}</h1>
        </div>
        {% if not user_loans %}
        <div class="mt-10">
        <i class="bi bi-exclamation-triangle-fill text-2xl" style="color: rgb(248 113 113);"></i>
        </div>
        <p>No loans found</p>
        {% else %}
    </div>
    <div>
        <ul class="flex list-none flex-row flex-wrap border-b-0 pl-0" id="tabs-tab3" role="tablist" data-te-nav-ref>
            <li role="presentation">
                <a href="#tabs-home3"
                    class=" inline-block p-2 border-b-2 border-transparent bg-red-400 text-white rounded-t-lg hover:underline hover:bg-red-400 "
                    id="tabs-home-tab3" data-te-toggle="pill" data-te-target="#tabs-home3" data-te-nav-active role="tab"
                    aria-controls="tabs-home3" aria-selected="true">Loans</a>

            </li>
            <li role="presentation">
                <a href="#tabs-profile3"
                    class="inline-block p-2 border-b-2 border-transparent bg-red-300 text-white rounded-t-lg hover:underline hover:bg-red-400"
                    id="tabs-profile-tab3" data-te-toggle="pill" data-te-target="#tabs-profile3" role="tab"
                    aria-controls="tabs-profile3" aria-selected="false">History</a>
            </li>
        </ul>
    </div>

    <div class="h-[height-value] overflow-y-auto">
        <div class="hidden opacity-100 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
            id="tabs-home3" role="tabpanel" data-te-tab-active aria-labelledby="tabs-home-tab3">
            <div class="container px-2 sm:px-0 text-center">
                {% for event in user_loans reversed %}
                {% if forloop.first %}

                <table class=" w-full bg-white rounded-lg shadow-md text-sm mx-auto">
                    <thead class="bg-gray-200">
                        <tr>
                            <th class="p-2">ID</th>

                            <th class="p-2">Name</th>
                            <th class="p-2">Loan Date</th>
                            <th class="p-2">Return Date</th>
                            <th class="p-2">Late?</th>
                            <th class="p-2">Action</th>
                        </tr>
                    </thead>
                    {% endif %}
                    <tbody>
                        {% if event.actual_return_date == None %}

                        <tr class="border-t border-gray-300 ">
                            <td class="p-2">{{ event.id }}</td>
                            <td class="p-2"> {{ event.product.name }}</td>
                            <td class="p-2">{{ event.loaned_date|date:"d.m.Y" }}</td>
                            <td class="p-2">{{ event.return_date|date:"d.m.Y" }}</td>

                            <td class="p-2">
                                {% if current_date > event.return_date %}

                                <i class="bi bi-exclamation-circle-fill" style="color: rgb(248 113 113);"></i>
                                {% else %}
                                -
                                {% endif %}

                            </td>

                            <td class="p-2">
                                <form method="post" action="{% url 'account:return_loan' %}">
                                    {% csrf_token %}

                                    <input type="hidden" name="loan_id" value="{{ event.id }}">
                                    <button type="submit"
                                        class="bg-red-400 text-white py-2 px-4 rounded hover:underline">Return</button>
                            </td>
                        </tr>


                        {% endif %}

                        {% endfor %}
                    </tbody>
                </table>

            </div>

        </div>
        <div class="hidden opacity-0 transition-opacity duration-150 ease-linear data-[te-tab-active]:block"
            id="tabs-profile3" role="tabpanel" aria-labelledby="tabs-profile-tab3">
            <div class="container px-2 sm:px-0 text-center">
                {% for event in user_loans reversed %}
                {% if forloop.first %}

                <table class=" bg-white rounded-lg shadow-md text-sm mx-auto w-full">
                    <thead class="bg-gray-200">
                        <tr>
                            <th class="p-2">ID</th>

                            <th class="p-2">Name</th>
                            <th class="p-2">Loan Date</th>
                            <th class="p-2">Date Returned</th>
                        </tr>
                    </thead>
                    {% endif %}
                    {% if event.actual_return_date != None %}

                    <tbody>

                        <tr class="border-t border-gray-300">
                            <td class="p-2">{{ event.id }}</td>

                            <td class="p-2"> {{ event.product.name }}</td>
                            <td class="p-2">{{ event.loaned_date|date:"d.m.Y" }}</td>
                            <td class="p-2">{{ event.actual_return_date|date:"d.m.Y" }}</td>

                        </tr>


                        {% endif %}

                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </section>
    {% endif %}


</div>



{% endblock %}